/** Convocados Argentina Mundial 2026 */
export const ARGENTINA_SQUAD = [
  // Arqueros
  { name: 'Emiliano "Dibu" Martinez', pos: 'POR' },
  { name: 'Geronimo Rulli', pos: 'POR' },
  { name: 'Juan Musso', pos: 'POR' },
  // Defensores
  { name: 'Leonardo Balerdi', pos: 'DEF' },
  { name: 'Nicolas Tagliafico', pos: 'DEF' },
  { name: 'Gonzalo Montiel', pos: 'DEF' },
  { name: 'Lisandro Martinez', pos: 'DEF' },
  { name: 'Cristian Romero', pos: 'DEF' },
  { name: 'Nicolas Otamendi', pos: 'DEF' },
  { name: 'Facundo Medina', pos: 'DEF' },
  { name: 'Nahuel Molina', pos: 'DEF' },
  // Mediocampistas
  { name: 'Leandro Paredes', pos: 'MED' },
  { name: 'Rodrigo De Paul', pos: 'MED' },
  { name: 'Valentin Barco', pos: 'MED' },
  { name: 'Giovani Lo Celso', pos: 'MED' },
  { name: 'Exequiel Palacios', pos: 'MED' },
  { name: 'Alexis Mac Allister', pos: 'MED' },
  { name: 'Enzo Fernandez', pos: 'MED' },
  // Delanteros
  { name: 'Julian Alvarez', pos: 'DEL' },
  { name: 'Lionel Messi', pos: 'DEL' },
  { name: 'Nico Gonzalez', pos: 'DEL' },
  { name: 'Thiago Almada', pos: 'DEL' },
  { name: 'Giuliano Simeone', pos: 'DEL' },
  { name: 'Nico Paz', pos: 'DEL' },
  { name: 'Jose Manuel Lopez', pos: 'DEL' },
  { name: 'Lautaro Martinez', pos: 'DEL' },
]

/** Los 48 equipos clasificados al Mundial 2026 */
export const WORLD_CUP_TEAMS = [
  'Argentina',
  'Alemania',
  'Arabia Saudita',
  'Argelia',
  'Australia',
  'Austria',
  'Bélgica',
  'Bosnia y Herzegovina',
  'Brasil',
  'Cabo Verde',
  'Canadá',
  'Colombia',
  'Corea del Sur',
  'Costa de Marfil',
  'Croacia',
  'Curazao',
  'Ecuador',
  'Egipto',
  'Escocia',
  'España',
  'Estados Unidos',
  'Francia',
  'Ghana',
  'Haití',
  'Inglaterra',
  'Irán',
  'Irak',
  'Japón',
  'Jordania',
  'Marruecos',
  'México',
  'Noruega',
  'Nueva Zelanda',
  'Países Bajos',
  'Panamá',
  'Paraguay',
  'Portugal',
  'Qatar',
  'República Checa',
  'República Democrática del Congo',
  'Senegal',
  'Sudáfrica',
  'Suecia',
  'Suiza',
  'Túnez',
  'Turquía',
  'Uruguay',
  'Uzbekistán',
]
