/** Convocados Argentina Mundial 2026 */
export const ARGENTINA_SQUAD = [
  // Arqueros
  { name: 'Emiliano "Dibu" Martinez', pos: 'POR' },
  { name: 'Geronimo Rulli', pos: 'POR' },
  { name: 'Juan Musso', pos: 'POR' },
  // Defensores
  { name: 'Leonardo Balerdi', pos: 'DEF' },
  { name: 'Nicolas Tagliafico', pos: 'DEF' },
  { name: 'Gonzalo Montiel', pos: 'DEF' },
  { name: 'Lisandro Martinez', pos: 'DEF' },
  { name: 'Cristian Romero', pos: 'DEF' },
  { name: 'Nicolas Otamendi', pos: 'DEF' },
  { name: 'Facundo Medina', pos: 'DEF' },
  { name: 'Nahuel Molina', pos: 'DEF' },
  // Mediocampistas
  { name: 'Leandro Paredes', pos: 'MED' },
  { name: 'Rodrigo De Paul', pos: 'MED' },
  { name: 'Valentin Barco', pos: 'MED' },
  { name: 'Giovani Lo Celso', pos: 'MED' },
  { name: 'Exequiel Palacios', pos: 'MED' },
  { name: 'Alexis Mac Allister', pos: 'MED' },
  { name: 'Enzo Fernandez', pos: 'MED' },
  // Delanteros
  { name: 'Julian Alvarez', pos: 'DEL' },
  { name: 'Lionel Messi', pos: 'DEL' },
  { name: 'Nico Gonzalez', pos: 'DEL' },
  { name: 'Thiago Almada', pos: 'DEL' },
  { name: 'Giuliano Simeone', pos: 'DEL' },
  { name: 'Nico Paz', pos: 'DEL' },
  { name: 'Jose Manuel Lopez', pos: 'DEL' },
  { name: 'Lautaro Martinez', pos: 'DEL' },
]

/** Los 48 equipos del Mundial 2026 — en español, ordenados alfabéticamente */
export const WORLD_CUP_TEAMS = [
  'Alemania',
  'Argelia',
  'Argentina',
  'Arabia Saudita',
  'Australia',
  'Austria',
  'Bolivia',
  'Bosnia',
  'Brasil',
  'Camerun',
  'Canada',
  'Cabo Verde',
  'Chile',
  'China',
  'Colombia',
  'Congo RD',
  'Corea del Sur',
  'Costa de Marfil',
  'Costa Rica',
  'Croacia',
  'Curacao',
  'Ecuador',
  'Egipto',
  'Eslovaquia',
  'Eslovenia',
  'Espana',
  'Estados Unidos',
  'Francia',
  'Gales',
  'Georgia',
  'Ghana',
  'Haiti',
  'Honduras',
  'Hungria',
  'Indonesia',
  'Inglaterra',
  'Iran',
  'Irak',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kenia',
  'Mali',
  'Marruecos',
  'Mexico',
  'Nigeria',
  'Nueva Zelanda',
  'Paisas Bajos',
  'Panama',
  'Paraguay',
  'Peru',
  'Polonia',
  'Portugal',
  'Qatar',
  'Rumania',
  'Arabia Saudita',
  'Senegal',
  'Serbia',
  'Sudafrica',
  'Suecia',
  'Suiza',
  'Tunez',
  'Turquia',
  'Ucrania',
  'Uruguay',
  'Uzbekistan',
  'Venezuela',
].filter((v, i, a) => a.indexOf(v) === i).sort()
